import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'title': 'title',
          'change Language': 'Change Language',
          'Full Name': 'Full Name',
          'Email': 'Email',
          'Password': 'Password',
          'Enter your Email': 'Enter your Email',
          'Enter valid email': 'Enter valid email',
          'Enter your Password': 'Enter your Password',
          'Hello': 'Hello',
          'Welcome To Aman': 'Welcome To Aman',
          'Sign In': 'Sign In',
          'Register': 'Register',
          'Current Password': 'Current Password',
          'Type Your Current Password': 'Type Your Current Password',
          'New Password': 'New Password',
          'Type Your New Password': 'Type Your New Password',
          'Dark Mode': 'Dark Mode',
          'Change Language': 'Change Language',
          'Save': 'Save',
          'Cancel': 'Cancel',
          'Flat': 'Flat',
          'Building': 'Building',
          'Villa': 'villa',
          'Store': 'Store',
          'Clinic': 'Clinic',
          'Farm': 'Farm',
          'Factory': 'Factory',
          'Land': 'Land',
          'Other': 'Other',
          'For Sale': 'For Sale',
          'For Rent': 'For Rent',
          'Owner Number': 'Owner Number',
          'Select Number': 'Select Number',
          'Phone Numbers': 'Phone Numbers',
          'Call': 'Call',
          'Rooms': 'Rooms',
          'Barthrooms': 'Barthrooms',
          'Flats': 'Flats',
          'Furnished': 'Furnished',
          'Floor': 'Floor',
          'Type Of Activity': 'Type Of Activity',
          'Adminstrative Building': 'Adminstrative Building',
          'Finishing': 'Finishing',
          'Doublex': 'Doublex',
          'Priority': 'Priority',
          'Payment': 'Payment',
          'Owner Name': 'Owner Name',
          'Unit Name': 'Unit Name',
          'Price': 'Price',
          'Description For User': 'Description For User',
          'Description For Admin': 'Description For Admin',
          'Address For Admin': 'Address For Admin',
          'Address For User': 'Address For User',
          'Photos': 'Photos',
          'Cash': 'Cash',
          'installment': 'installment',
          'High': 'High',
          'medium': 'medium',
          'Low': 'Low',
          'Yes': 'Yes',
          'No': 'No',
          'Remember Me?': 'Remember Me?',
          'Forgot Password?': 'Forgot Password?',
          'Sign Up': 'Sign Up',
          'Confirm your Password': 'Confirm your Password',
          'Search': 'Search',
          'Properties': 'Properties',
          'Low To High': 'Low To High',
          'High To Low': 'High To Low',
          'Filter': 'Filter',
          'your search': 'your search',
          'Bathrooms': 'Bathrooms',
          'Sign out': 'Sign out',
          'Your Wishlist': 'Your Wishlist',
          'Home': 'Home',
          'Likes': 'Likes',
          'Profile': 'Profile',
          'Rents': 'Rents',
          'Dashboard': 'Dashboard',
          'Paid': 'Paid',
          'Not Paid': 'Not Paid',
          'New Contract': 'New Contract',
          'Expired contract': 'Expired contract',
          'Update Rents Data': 'Update Rents Data',
          'Gets Rents Data!': 'Gets Rents Data!',
          'Add Rent': 'Add Rent',
          'Select Type': 'Select Type',
          'Area': 'Area',
          'Lessor Name': 'Lessor Name',
          'Lessor Number': 'Lessor Number',
          'Tenant Name': 'Tenant Name',
          'Tenant Number': 'Tenant Number',
          'Description': 'Description',
          'Select yes if Furnished': 'Select yes if Furnished',
          'Select Finishing': 'Select Finishing',
          'Half': 'Half',
          'Submit': 'Submit',
          'Start Of Contract': 'Start Of Contract',
          'End Of Contract': 'End Of Contract',
          'Start Of Rent': 'Start Of Rent',
          'End Of Rent': 'End Of Rent',
          'Error': 'Error',
          'Please Put all Dates Right': 'Please Put all Dates Right',
          'Select Date': 'Select Date',
          'Please Select': 'Please Select',
          'Please enter a valid': 'Please enter a valid',
          'Edit Rent': 'Edit Rent',
          'Change Rent Date?': 'Change Rent Date?',
          'Payed': 'Payed',
          'DidntPay': 'DidntPay',
          'DidntStart': 'DidntStart',
          'Finished': 'Finished',
          'Delete': 'Delete',
          'Success': 'Success',
          'Successfully deleted property': 'Successfully deleted property',
          'Are you sure you would like to delete this property?':
              'Are you sure you would like to delete this property?',
          'Add': 'Add',
          'Please upload images': 'Please upload images',
          'Please Choose a type!': 'Please Choose a type!',
          'Uploading': 'Uploading',
          'Uploading to database': 'Uploading to database',
          'Number Of Floors': 'Number Of Floors',
          'Number Of administrative buildings':
              'Number Of administrative buildings',
          'Number Of Flats': 'Number Of Flats',
          'Upload main image': 'Upload main image',
          'Upload Multiple Sub-Images': 'Upload Multiple Sub-Images',
          '(Limit 20 Images Only!)': '(Limit 20 Images Only!)',
          'Select Payment Method': 'Select Payment Method',
          'Select priority': 'Select priority',
          'Select visibility': 'Select visibility',
          'Select offering': 'Select offering',
          'Select yes if Doublex': 'Select yes if Doublex',
          'Edit': 'Edit',
          'Edit main image': 'Edit main image',
          'Edit Multiple Sub-Images': 'Edit Multiple Sub-Images',
          'Any': 'Any',
          'Type': 'Type',
          'Add Custom Days': 'Add Custom Days',
          'Add 30 Days': 'Add 30 Days',
          'Start and End of Rent Differing': 'Start and End of Rent Differing',
          'How Many Days?': 'How Many Days?',
          'Filtered Properties': 'Filtered Properties',
          'Searched Properties': 'Searched Properties',
          'name': 'name',
          'number': 'number',
          'Cant add more than 10 numbers please delete one to add another':
              'Cant add more than 10 numbers please delete one to add another',
          'Add Number': 'Add Number',
          'Admin Numbers': 'Admin Numbers',
          'Units': 'Units',
          'Users': 'Users',
          'No Data is Found': 'No Data is Found',
          'Successfully Added Property': 'Successfully Added Property',
          'Search By Lessor': 'Search By Lessor',
          'Your WishList is Empty': 'Your WishList is Empty',
          'Explore more and shortlist some items':
              'Explore more and shortlist some items',
          'Start Shopping': 'Start Shopping',
        },
        //arabic LANGUAGE

        'ar_EG': {
          'title': 'عنوان',
          'change Language': 'تغير اللغة',
          'Full Name': 'الاسم الكامل',
          'Email': 'البريد الالكتروني',
          'Password': 'كلمه المرور',
          'Enter your Email': 'ادخل البريد الالكتروني',
          'Enter valid email': 'ادخل بريد الكتروني صحيح',
          'Enter your Password': 'ادخل كلمة المرور',
          'Hello': 'أهلا',
          'Welcome To Aman': 'مرحبا بك في أمان',
          'Sign In': 'تسجيل الدخول',
          'Register': 'أنشاء حساب',
          'Current Password': 'كلمة المرور الحالية',
          'Type Your Current Password': 'اكنب كلمة المرور الحالية',
          'New Password': 'كلمة المرور الجديدة',
          'Type Your New Password': 'اكتب كلمة المرور الجديدة',
          'Dark Mode': 'الوضع الليلي:',
          'Change Language': 'تغيير اللغة',
          'Save': 'حفظ',
          'Cancel': 'الغاء',
          'Flat': 'شقة',
          'Building': 'عمارة',
          'Villa': 'فيلا',
          'Store': 'محل',
          'Clinic': 'عيادة',
          'Farm': 'مزرعة',
          'Factory': 'مصنع',
          'Land': 'أرض',
          'Other': 'أخري',
          'For Sale': 'للبيع',
          'For Rent': 'للايجار',
          'Owner Number': 'رقم صاحب العقار',
          'Select Number': 'أختر رقم',
          'Phone Numbers': 'أرقام الهاتف',
          'Call': 'اتصال',
          'Rooms': 'غرف',
          'Barthrooms': 'حمامات',
          'Flats': 'شقق',
          'Furnished': 'مفروش',
          'Floor': 'الدور',
          'Type Of Activity': 'نوع النشاط',
          'Adminstrative Building': 'المباني الاداريه',
          'Finishing': 'تشطيب',
          'Doublex': 'دوبليكس',
          'Priority': 'الاهمية',
          'Payment': 'طريقه الدفع',
          'Owner Name': 'اسم صاحب العقار',
          'Unit Name': 'اسم العقار',
          'Price': 'السعر',
          'Description For User': 'الوصف',
          'Description For Admin': 'الوصف للأدمن',
          'Address For Admin': 'العنوان للأدمن',
          'Address For User': 'العنوان',
          'Photos': 'الصور',
          'Cash': 'كاش',
          'installment': 'تقسيط',
          'High': 'مرتفع',
          'medium': 'متوسط',
          'Low': 'منخفض',
          'Yes': 'نعم',
          'No': 'لا',
          'Remember Me?': 'تذكرني ؟',
          'Forgot Password?': 'هل نسيت كلمه المرور؟',
          'Sign Up': 'اشتراك',
          'Confirm your Password': 'أكد كلمة المرور',
          'Search': 'بحث',
          'Properties': 'عقار',
          'Low To High': 'من الأقل الى الأعلى',
          'High To Low': 'من الأعلى الى الأقل',
          'Filter': 'فلتر',
          'your search': 'البحث الخاص بك',
          'Bathrooms': 'حمامات',
          'Sign out': 'تسجيل الخروج',
          'Your Wishlist': 'قائمة امنياتك',
          'Home': 'الرئيسية',
          'Likes': 'المفضلة',
          'Profile': 'تعديل',
          'Rents': 'الايجارات',
          'Dashboard': 'لوحة التحكم',
          'Paid': 'تم الدفع',
          'Not Paid': 'لم يدفع',
          'New Contract': 'عقد جديد',
          'Expired contract': 'عقود منتهية',
          'Update Rents Data': 'تحديث بيانات الأيجارات',
          'Gets Rents Data!': 'الحصول على بيانات الايجارات',
          'Add Rent': 'اضافة ايجار',
          'Select Type': 'أختر النوع',
          'Area': 'مساحة',
          'Lessor Name': 'أسم المؤجر',
          'Lessor Number': 'رقم المؤجر',
          'Tenant Name': 'أسم المستأجر',
          'Tenant Number': 'رقم المستأجر',
          'Description': 'الوصف',
          'Select yes if Furnished': 'أختر نعم إذا كانت مفروشة',
          'Select Finishing': 'أختر حالة التشطيب',
          'Half': 'نصف تشطيب',
          'Submit': 'تأكيد',
          'Start Of Contract': 'بداية العقد',
          'End Of Contract': 'نهاية العقد',
          'Start Of Rent': 'بداية الإيجار',
          'End Of Rent': 'نهاية الإيجار',
          'Error': 'خطأ',
          'Please Put all Dates Right': 'برجاء ادخال التواريخ الصحيحة',
          'Select Date': 'أختر تاريخ',
          'Please Select': 'برجاء الاختيار',
          'Please enter a valid': 'برجاء اختيار ',
          'Edit Rent': 'تعديل الإيجار',
          'Change Rent Date?': 'تغير تاريخ الإيجار؟',
          'Payed': 'تم الدفع',
          'DidntPay': 'لم يدفع',
          'DidntStart': 'عقد جديد',
          'Finished': 'عقود منتهية',
          'Delete': 'حذف',
          'Success': 'نجاح',
          'Successfully deleted property': 'تم الحذف بنجاح',
          'Are you sure you would like to delete this property?':
              'هل انت متأكد من انك تريد الحذف؟',
          'Add': 'أضافة',
          'Please upload images': 'الرجاء تحميل الصور',
          'Please Choose a type!': 'الرجاء اختيار نوع',
          'Uploading': 'جاري التحميل',
          'Uploading to database': 'التحميل الى قاعدة البيانات',
          'Number Of Floors': 'عدد الادوار',
          'Number Of administrative buildings': 'عدد المباني الأدارية',
          'Number Of Flats': 'عدد الشقق',
          'Upload main image': 'تحميل الصورة الرئيسية',
          'Upload Multiple Sub-Images': 'تحميل الصور المتعددة',
          '(Limit 20 Images Only!)': 'حد اقصى 20 صورة',
          'Select Payment Method': 'أختر طريقة الدفع',
          'Select priority': 'أختر الأهمية',
          'Select visibility': 'أختر الظهور للمستخدم',
          'Select offering': 'أختر نوع العقد',
          'Select yes if Doublex': 'أختر نعم اذا كانت دوبليكس',
          'Edit': 'تعديل',
          'Edit main image': 'تعديل الصورة الرئيسية',
          'Edit Multiple Sub-Images': 'تعديل الصور الفرعية',
          'Any': 'أي شئ',
          'Type': 'نوع',
          'Add Custom Days': 'أضف عدد الايام',
          'Add 30 Days': 'أضافة 30 يوم',
          'Start and End of Rent Differing': 'الفرق بين بداية ونهاية الايجار',
          'How Many Days?': 'كم عدد الايام؟',
          'Filtered Properties': 'عقار',
          'Searched Properties': 'عقار من نواتج البحث',
          'name': 'الأسم',
          'number': 'الرقم',
          'Cant add more than 10 numbers please delete one to add another':
              'لا يمكن أضافة اكثر من 10 أرقام الرجاء مسح رقم لاأضافة الأخر',
          'Add Number': 'أضافة رقم',
          'Admin Numbers': 'أرقام المشرفين',
          'Units': 'عقارات',
          'Users': 'المستخدمين',
          'No Data is Found': 'لم يتم العثور علي شئ',
          'Search By Lessor': 'بحث عن المؤجر'
        },
      };
}
