import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'title': 'title',
          'change Language': 'Change Language',
          'Full Name': 'Full Name',
          'Email': 'Email',
          'Password': 'Password',
          'Enter your Email': 'Enter your Email',
          'Enter valid email': 'Enter valid email',
          'Enter your Password': 'Enter your Password',
          'Hello': 'Hello',
          'Welcome To Aman': 'Welcome To Aman',
          'Sign In': 'Sign In',
          'Register': 'Register',
          'Current Password': 'Current Password',
          'Type Your Current Password': 'Type Your Current Password',
          'New Password': 'New Password',
          'Type Your New Password': 'Type Your New Password',
          'Dark Mode': 'Dark Mode',
          'Change Language': 'Change Language',
          'Save': 'Save',
          'Cancel': 'Cancel',
          'Flat': 'Flat',
          'Building': 'Building',
          'Villa': 'villa',
          'Store': 'Store',
          'Clinic': 'Clinic',
          'Farm': 'Farm',
          'Factory': 'Factory',
          'Land': 'Land',
          'Other': 'Other',
          'For Sale': 'For Sale',
          'For Rent': 'For Rent',
          'Owner Number': 'Owner Number',
          'Select Number': 'Select Number',
          'Phone Numbers': 'Phone Numbers',
          'Call': 'Call',
          'Rooms': 'Rooms',
          'Barthrooms': 'Barthrooms',
          'Flats': 'Flats',
          'Furnished': 'Furnished',
          'Floor': 'Floor',
          'Type Of Activity': 'Type Of Activity',
          'Adminstrative Building': 'Adminstrative Building',
          'Finishing': 'Finishing',
          'Doublex': 'Doublex',
          'Priority': 'Priority',
          'Payment': 'Payment',
          'Owner Name': 'Owner Name',
          'Unit Name': 'Unit Name',
          'Price': 'Price',
          'Description For User': 'Description For User',
          'Description For Admin': 'Description For Admin',
          'Address For Admin': 'Address For Admin',
          'Address For User': 'Address For User',
          'Photos': 'Photos',
          'Cash': 'Cash',
          'installment': 'installment',
          'High': 'High',
          'medium': 'medium',
          'Low': 'Low',
          'Yes': 'Yes',
          'No': 'No',
          'Remember Me?': 'Remember Me?',
          'Forgot Password?': 'Forgot Password?',
          'Sign Up': 'Sign Up',
          'Confirm your Password': 'Confirm your Password',
          'Search': 'Search',
          'Properties': 'Properties',
          'Low To High': 'Low To High',
          'High To Low': 'High To Low',
          'Filter': 'Filter',
          'your search': 'your search',
          'Bathrooms': 'Bathrooms',
          'Sign out': 'Sign out',
          'Your Wishlist': 'Your Wishlist',
          'Home': 'Home',
          'Likes': 'Likes',
          'Profile': 'Profile',
          'Rents': 'Rents',
          'Dashboard': 'Dashboard'
        },
        //arabic LANGUAGE

        'ar_EG': {
          'title': 'عنوان',
          'change Language': 'تغير اللغة',
          'Full Name': 'الاسم الكامل',
          'Email': 'البريد الالكتروني',
          'Password': 'كلمه المرور',
          'Enter your Email': 'ادخل البريد الالكتروني',
          'Enter valid email': 'ادخل بريد الكتروني صحيح',
          'Enter your Password': 'ادخل كلمة المرور',
          'Hello': 'أهلا',
          'Welcome To Aman': 'مرحبا بك في أمان',
          'Sign In': 'تسجيل الدخول',
          'Register': 'أنشاء حساب',
          'Current Password': 'كلمة المرور الحالية',
          'Type Your Current Password': 'اكنب كلمة المرور الحالية',
          'New Password': 'كلمة المرور الجديدة',
          'Type Your New Password': 'اكتب كلمة المرور الجديدة',
          'Dark Mode': 'الوضع الليلي:',
          'Change Language': 'تغيير اللغة',
          'Save': 'حفظ',
          'Cancel': 'الغاء',
          'Flat': 'شقة',
          'Building': 'عمارة',
          'Villa': 'فيلا',
          'Store': 'محل',
          'Clinic': 'عيادة',
          'Farm': 'مزرعة',
          'Factory': 'مصنع',
          'Land': 'أرض',
          'Other': 'أخري',
          'For Sale': 'للبيع',
          'For Rent': 'للايجار',
          'Owner Number': 'رقم صاحب العقار',
          'Select Number': 'أختر رقم',
          'Phone Numbers': 'أرقام الهاتف',
          'Call': 'اتصال',
          'Rooms': 'غرف',
          'Barthrooms': 'حمامات',
          'Flats': 'شقق',
          'Furnished': 'مفروش',
          'Floor': 'الدور',
          'Type Of Activity': 'نوع النشاط',
          'Adminstrative Building': 'المباني الاداريه',
          'Finishing': 'تشطيب',
          'Doublex': 'دوبليكس',
          'Priority': 'الاهمية',
          'Payment': 'طريقه الدفع',
          'Owner Name': 'اسم صاحب العقار',
          'Unit Name': 'اسم العقار',
          'Price': 'السعر',
          'Description For User': 'الوصف',
          'Description For Admin': 'الوصف للأدمن',
          'Address For Admin': 'العنوان للأدمن',
          'Address For User': 'العنوان',
          'Photos': 'الصور',
          'Cash': 'كاش',
          'installment': 'تقسيط',
          'High': 'مرتفع',
          'medium': 'متوسط',
          'Low': 'منخفض',
          'Yes': 'نعم',
          'No': 'لا',
          'Remember Me?': 'تذكرني ؟',
          'Forgot Password?': 'هل نسيت كلمه المرور؟',
          'Sign Up': 'اشتراك',
          'Confirm your Password': 'أكد كلمة المرور',
          'Search': 'بحث',
          'Properties': 'عقارات',
          'Low To High': 'من الأقل الى الأعلى',
          'High To Low': 'من الأعلى الى الأقل',
          'Filter': 'فلتر',
          'your search': 'البحث الخاص بك',
          'Bathrooms': 'حمامات',
          'Sign out': 'تسجيل الخروج',
          'Your Wishlist': 'قائمة امنياتك',
          'Home': 'الرئيسية',
          'Likes': 'المفضلة',
          'Profile': 'تعديل',
          'Rents': 'الايجارات',
          'Dashboard': 'لوحة التحكم'
        },
      };
}
